FUNC LABEL 0
    MOV REG 0 VAL 5
    MOV REG 0 VAL 150
    CAL VAL 1
    ADD REG 0 REG 1
    PRINT REG 0
    NOT REG 0
    PRINT REG 0
    RET
FUNC LABEL 1
    MOV REG 1 VAL 25
    PRINT REG 1
    RET
