FUNC LABEL 0
    MOV STK A VAL 10
    REF REG 0 STK A
    CAL VAL 1
    PRINT STK A
    RET
FUNC LABEL 1
    MOV STK A REG 0
    REF REG 0 STK A
    CAL VAL 2
    RET
FUNC LABEL 2
    MOV STK A REG 0
    REF REG 0 STK A
    CAL VAL 3
    RET
FUNC LABEL 3
    MOV STK A REG 0
    MOV STK B PTR A
    MOV STK C PTR B
    MOV PTR C VAL 100
    RET
